import { useState } from 'react';
import { Image, ImageBackground, Modal, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Colors } from '../constants/Colors';
import type { RootStackParamList } from '../App';
type Props=NativeStackScreenProps<RootStackParamList,'DumpDetail'>;
const full='https://images.unsplash.com/photo-1566737236500-c8ac43014a67?auto=format&fit=crop&w=1200&q=90';
const photos=[full,'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=800&q=85','https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?auto=format&fit=crop&w=800&q=85','https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=800&q=85'];
export default function DumpDetailScreen({navigation}:Props){const [color,setColor]=useState<number|null>(null);const [viewer,setViewer]=useState<number|null>(null);return <SafeAreaView style={s.safe}><View style={s.header}><Pressable style={s.back} onPress={()=>navigation.goBack()}><Text style={s.backText}>‹</Text></Pressable><Pressable style={s.share} onPress={()=>navigation.navigate('Invite',{dumpId:'no-sleep'})}><Text style={s.shareText}>⇧</Text></Pressable></View><View style={s.rule}/><ScrollView showsVerticalScrollIndicator={false}><ImageBackground source={{uri:full}} style={s.cover}><View style={s.coverShade}/><View style={s.live}><Text style={s.liveText}>LIVE</Text></View><View style={s.coverContent}><Text style={s.date}>24 SEP 2026 · BROOKLYN</Text><Text style={s.title}>NO SLEEP{`\n`}TILL MONDAY</Text><Text style={s.stats}>186 PHOTOS      31 PEOPLE</Text></View></ImageBackground><View style={s.gridHeader}><Text style={s.gridLabel}>EVERYONE’S POV</Text><Text style={s.add}>＋  ADD YOURS</Text></View><View style={s.grid}>{photos.map((uri,index)=><Pressable key={uri} style={s.photo} onLongPress={()=>setColor(index)} onPressOut={()=>setColor(null)} onPress={()=>setViewer(index)}><Image source={{uri:color===index?uri:`${uri}&sat=-100`}} style={s.photoImage}/></Pressable>)}</View></ScrollView><Modal visible={viewer!==null} animationType="fade" onRequestClose={()=>setViewer(null)}><View style={s.viewer}><Image source={{uri:viewer===null?full:photos[viewer]}} style={s.viewerImage} resizeMode="contain"/><Pressable style={s.close} onPress={()=>setViewer(null)}><Text style={s.closeText}>×</Text></Pressable><Text style={s.viewerHint}>TAP × TO CLOSE</Text></View></Modal></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#000'},header:{height:100,paddingHorizontal:32,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},back:{width:70,height:70,borderWidth:1,borderColor:'#444',justifyContent:'center',alignItems:'center'},backText:{fontSize:54,color:'#fff',fontWeight:'200',marginTop:-10},share:{width:70,height:70,borderWidth:1,borderColor:'#444',justifyContent:'center',alignItems:'center'},shareText:{color:'#fff',fontSize:41,fontWeight:'200'},rule:{height:StyleSheet.hairlineWidth,backgroundColor:'#222',marginHorizontal:18},cover:{height:760,justifyContent:'flex-end'},coverShade:{...StyleSheet.absoluteFill,backgroundColor:'rgba(0,0,0,.38)'},live:{position:'absolute',top:30,left:32,backgroundColor:Colors.accent,paddingVertical:10,paddingHorizontal:14},liveText:{fontSize:13,fontWeight:'900'},coverContent:{padding:32,paddingBottom:40},date:{color:Colors.accent,fontSize:14,fontWeight:'900',letterSpacing:1.7,marginBottom:27},title:{color:'#fff',fontSize:56,lineHeight:52,letterSpacing:-2.5,fontWeight:'900'},stats:{color:'#aaa',fontSize:14,letterSpacing:1.3,fontWeight:'900',marginTop:30},gridHeader:{borderTopWidth:StyleSheet.hairlineWidth,borderBottomWidth:StyleSheet.hairlineWidth,borderColor:'#333',height:110,marginHorizontal:18,paddingHorizontal:14,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},gridLabel:{color:'#999',fontWeight:'900',fontSize:14,letterSpacing:1.7},add:{color:Colors.accent,fontWeight:'900',fontSize:15,letterSpacing:1.2},grid:{flexDirection:'row',flexWrap:'wrap',gap:4,padding:18},photo:{width:'49.4%',height:220,backgroundColor:'#222',overflow:'hidden'},photoImage:{width:'100%',height:'100%'},viewer:{flex:1,backgroundColor:'#000',justifyContent:'center'},viewerImage:{width:'100%',height:'78%'},close:{position:'absolute',right:26,top:65,width:54,height:54,borderWidth:1,borderColor:'#666',alignItems:'center',justifyContent:'center'},closeText:{fontSize:38,color:'#fff',fontWeight:'200'},viewerHint:{position:'absolute',bottom:55,width:'100%',textAlign:'center',color:'#999',fontSize:13,fontWeight:'900',letterSpacing:1.5}});
