import { useState } from 'react';
import { ImageBackground, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Colors } from '../constants/Colors';
import type { RootStackParamList } from '../App';

type Props = NativeStackScreenProps<RootStackParamList, 'Home'>;
const cover = 'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?auto=format&fit=crop&w=1200&q=85&sat=-100';
const cards = [
  { title: 'NO SLEEP\nTILL MONDAY', date: '24 SEP 2026 · 186 PHOTOS', people: '31 PEOPLE', image: cover, live: true },
  { title: 'ROOFTOP\nSEASON', date: '11 JUL 2026', image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=800&q=85&sat=-100' },
  { title: 'NYE.\nNO CONTEXT', date: '01 JAN 2026', image: 'https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=800&q=85&sat=-100' },
];

export default function HomeScreen({ navigation }: Props) {
  // Switch to true while styling the populated state; real data will replace this.
  const [showDumps, setShowDumps] = useState(false);
  return <SafeAreaView style={styles.safe}>
    <View style={styles.header}>
      <Pressable accessibilityRole="button" accessibilityLabel="Create a dump" style={styles.iconButton} onPress={() => navigation.navigate('CreateDump')}><Text style={styles.plus}>+</Text></Pressable>
      <Pressable accessibilityRole="button" accessibilityLabel="Toggle demo dumps" onLongPress={() => setShowDumps((visible) => !visible)}>
        <ImageBackground source={require('../assets/images/AFTR_logo..png')} style={styles.logo} resizeMode="contain" />
      </Pressable>
      <Pressable accessibilityRole="button" accessibilityLabel="Join a dump with QR code" style={styles.iconButton} onPress={() => navigation.navigate('JoinDump')}><Text style={styles.scan}>⌗</Text></Pressable>
    </View><View style={styles.rule} />
    {showDumps ? <DumpList navigation={navigation} /> : <EmptyState navigation={navigation} />}
  </SafeAreaView>;
}
function EmptyState({ navigation }: Pick<Props, 'navigation'>) { return <View style={styles.empty}><View><Text style={styles.eyebrow}>NO RECAPS. JUST PROOF.</Text><Text style={styles.hero}>THE PARTY{`\n`}LIVES ON{`\n`}AFTR<Text style={styles.dot}>.</Text></Text><Text style={styles.subhead}>Create or join a Dump to get started</Text></View><View style={styles.emptyActions}><Pressable style={styles.primary} onPress={() => navigation.navigate('CreateDump')}><Text style={styles.primaryText}>CREATE A DUMP</Text></Pressable><Pressable style={styles.secondary} onPress={() => navigation.navigate('JoinDump')}><Text style={styles.secondaryText}>JOIN A DUMP</Text></Pressable></View></View>; }
function DumpList({ navigation }: Pick<Props, 'navigation'>) { return <ScrollView contentContainerStyle={styles.list} showsVerticalScrollIndicator={false}><Text style={styles.listEyebrow}>YOUR NIGHT, EVERY POV <Text style={styles.count}>03</Text></Text><Text style={styles.listTitle}>DUMPS</Text><Pressable onPress={() => navigation.navigate('DumpDetail', { dumpId: 'no-sleep' })}><DumpCard item={cards[0]} large /></Pressable><View style={styles.twoCards}>{cards.slice(1).map((item) => <Pressable key={item.title} style={styles.halfCard} onPress={() => navigation.navigate('DumpDetail', { dumpId: item.title })}><DumpCard item={item} /></Pressable>)}</View><Pressable style={styles.joinButton} onPress={() => navigation.navigate('JoinDump')}><Text style={styles.joinText}>⌗  JOIN A DUMP</Text></Pressable></ScrollView>; }
function DumpCard({ item, large = false }: { item: typeof cards[number]; large?: boolean }) { return <ImageBackground source={{ uri: item.image }} style={[styles.card, large ? styles.largeCard : styles.smallCard]} imageStyle={styles.cardImage}>{item.live && <View style={styles.live}><Text style={styles.liveText}>LIVE</Text></View>}<View style={styles.cardGradient} /><View style={styles.cardContent}><Text style={styles.cardDate}>{item.date}</Text><Text style={[styles.cardTitle, !large && styles.smallCardTitle]}>{item.title}</Text>{item.people && <Text style={styles.people}>{item.people}</Text>}</View></ImageBackground>; }
const styles = StyleSheet.create({ safe:{flex:1,backgroundColor:'#000'},header:{height:104,paddingHorizontal:24,alignItems:'center',justifyContent:'space-between',flexDirection:'row'},rule:{height:StyleSheet.hairlineWidth,backgroundColor:'#222',marginHorizontal:18},iconButton:{width:72,height:72,borderWidth:StyleSheet.hairlineWidth,borderColor:'#555',alignItems:'center',justifyContent:'center',borderRadius:3},plus:{color:'#fff',fontSize:48,fontWeight:'200',marginTop:-4},scan:{color:'#fff',fontSize:38,fontWeight:'600'},logo:{width:70,height:34},empty:{flex:1,paddingHorizontal:42,paddingTop:'48%',justifyContent:'space-between',paddingBottom:28},eyebrow:{color:'#999',fontSize:15,fontWeight:'900',letterSpacing:2.5},hero:{color:'#fff',fontSize:67,lineHeight:58,letterSpacing:-3.4,fontWeight:'900',marginTop:32},dot:{color:Colors.accent},subhead:{color:'#999',fontSize:20,marginTop:55},emptyActions:{gap:18},primary:{backgroundColor:Colors.accent,height:72,justifyContent:'center',alignItems:'center',borderRadius:2},primaryText:{fontSize:18,fontWeight:'900',color:'#000'},secondary:{borderColor:'#fff',borderWidth:1,height:72,justifyContent:'center',alignItems:'center',borderRadius:2},secondaryText:{color:'#fff',fontSize:18,fontWeight:'900'},list:{padding:26,paddingBottom:50},listEyebrow:{color:Colors.accent,fontSize:15,letterSpacing:2.4,fontWeight:'900',marginTop:32},count:{color:'#777',marginLeft:15},listTitle:{color:'#fff',fontSize:66,lineHeight:70,fontWeight:'900',letterSpacing:-3,marginBottom:30},card:{overflow:'hidden',backgroundColor:'#111'},cardImage:{opacity:.87},largeCard:{height:580},smallCard:{height:350},cardGradient:{...StyleSheet.absoluteFill,backgroundColor:'rgba(0,0,0,.36)'},live:{position:'absolute',top:20,left:20,zIndex:2,backgroundColor:Colors.accent,paddingHorizontal:13,paddingVertical:10},liveText:{color:'#000',fontWeight:'900',fontSize:13},cardContent:{position:'absolute',bottom:25,left:26,right:18},cardDate:{color:Colors.accent,fontSize:13,fontWeight:'900',letterSpacing:1.4,marginBottom:15},cardTitle:{color:'#fff',fontSize:50,lineHeight:48,letterSpacing:-2.4,fontWeight:'900'},smallCardTitle:{fontSize:30,lineHeight:28,letterSpacing:-1.2},people:{color:'#aaa',fontSize:13,letterSpacing:1.4,fontWeight:'800',marginTop:36},twoCards:{flexDirection:'row',gap:5,marginTop:5},halfCard:{flex:1},joinButton:{height:100,borderColor:'#fff',borderWidth:1,marginTop:62,alignItems:'center',justifyContent:'center'},joinText:{color:'#fff',fontWeight:'900',fontSize:17,letterSpacing:.2} });
