import { Pressable, SafeAreaView, Share, StyleSheet, Text, View } from 'react-native';
import QRCode from 'react-native-qrcode-svg';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Colors } from '../constants/Colors';
import type { RootStackParamList } from '../App';
type Props=NativeStackScreenProps<RootStackParamList,'Invite'>;
const inviteUrl='https://aftr.app/join/no-sleep';
export default function InviteScreen({navigation}:Props){const share=()=>Share.share({message:`Join my Dump: ${inviteUrl}`,url:inviteUrl});return <SafeAreaView style={s.safe}><View style={s.header}><Pressable style={s.back} onPress={()=>navigation.goBack()}><Text style={s.backText}>‹</Text></Pressable><Text style={s.live}>LIVE</Text></View><View style={s.rule}/><View style={s.content}><Text style={s.eyebrow}>NO SLEEP TILL MONDAY</Text><Text style={s.title}>MORE EYES.{`\n`}BETTER{`\n`}DUMP.</Text><Text style={s.sub}>Invite the group. One link, every POV.</Text><View style={s.qr}><QRCode value={inviteUrl} size={220} color="#000" backgroundColor="#fff"/></View><Text style={s.expiry}>SCAN TO JOIN · EXPIRES IN 48H</Text></View><View style={s.bottom}><Pressable style={s.copy} onPress={share}><Text style={s.copyText}>⌁   COPY INVITE LINK</Text></Pressable><View style={s.shareRow}><Pressable style={s.shareBox} onPress={share}><Text style={s.social}>IG</Text><Text style={s.socialSmall}>STORY</Text></Pressable><Pressable style={s.shareBox} onPress={share}><Text style={s.social}>WA</Text><Text style={s.socialSmall}>WHATSAPP</Text></Pressable><Pressable style={s.shareBox} onPress={share}><Text style={s.social}>•••</Text><Text style={s.socialSmall}>MORE</Text></Pressable></View></View></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#000'},header:{height:104,paddingHorizontal:32,alignItems:'center',justifyContent:'space-between',flexDirection:'row'},back:{width:70,height:70,borderWidth:1,borderColor:'#444',alignItems:'center',justifyContent:'center'},backText:{fontSize:54,color:'#fff',fontWeight:'200',marginTop:-10},live:{color:Colors.accent,fontSize:17,fontWeight:'900',letterSpacing:1.4},rule:{height:StyleSheet.hairlineWidth,backgroundColor:'#222',marginHorizontal:18},content:{padding:38,alignItems:'center',flex:1},eyebrow:{color:'#999',fontSize:15,letterSpacing:2.4,fontWeight:'900',marginTop:105},title:{color:'#fff',fontSize:57,lineHeight:53,letterSpacing:-2.6,fontWeight:'900',textAlign:'center',marginTop:30},sub:{color:'#999',fontSize:19,textAlign:'center',marginTop:32},qr:{backgroundColor:'#fff',padding:28,borderRadius:3,marginTop:80},expiry:{color:'#777',fontSize:13,fontWeight:'900',letterSpacing:1.6,marginTop:75},bottom:{borderTopWidth:StyleSheet.hairlineWidth,borderTopColor:'#333',padding:30,gap:19},copy:{backgroundColor:Colors.accent,height:72,alignItems:'center',justifyContent:'center',alignSelf:'flex-start',paddingHorizontal:22},copyText:{color:'#000',fontSize:17,fontWeight:'900'},shareRow:{height:105,flexDirection:'row'},shareBox:{flex:1,backgroundColor:'#101010',borderRightWidth:StyleSheet.hairlineWidth,borderRightColor:'#444',alignItems:'center',justifyContent:'center'},social:{color:'#fff',fontSize:22,fontWeight:'900'},socialSmall:{color:'#999',fontSize:11,fontWeight:'900',letterSpacing:1.3,marginTop:10}});
