import { useEffect, useState } from 'react';
import { Pressable, SafeAreaView, StyleSheet, Text, View } from 'react-native';
import { CameraView, useCameraPermissions } from 'expo-camera';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Colors } from '../constants/Colors';
import type { RootStackParamList } from '../App';
type Props = NativeStackScreenProps<RootStackParamList, 'JoinDump'>;
export default function JoinDumpScreen({navigation}:Props){const [permission,requestPermission]=useCameraPermissions();const [scanned,setScanned]=useState(false);useEffect(()=>{if(!permission) requestPermission();},[permission,requestPermission]);const onCode=()=>{if(!scanned){setScanned(true);navigation.replace('DumpDetail',{dumpId:'no-sleep'});}};return <SafeAreaView style={s.safe}><View style={s.header}><Pressable style={s.back} onPress={()=>navigation.goBack()}><Text style={s.backText}>‹</Text></Pressable><Text style={s.top}>SCAN</Text></View><View style={s.rule}/><View style={s.content}><Text style={s.eyebrow}>JOIN A DUMP</Text><Text style={s.title}>SCAN THE{`\n`}CODE.</Text><View style={s.cameraBox}>{permission?.granted&&<CameraView style={StyleSheet.absoluteFill} barcodeScannerSettings={{barcodeTypes:['qr']}} onBarcodeScanned={scanned?undefined:onCode}/>}<Corners/><View style={s.permission}>{!permission?.granted&&<><Text style={s.cameraIcon}>▣</Text><Text style={s.permissionTitle}>CAMERA ACCESS NEEDED</Text><Text style={s.permissionBody}>Allow camera access, then try again.</Text><Pressable style={s.allow} onPress={requestPermission}><Text style={s.allowText}>ALLOW CAMERA</Text></Pressable></>}</View></View><Text style={s.footer}>POINT YOUR CAMERA AT THE DUMP QR CODE</Text></View></SafeAreaView>}
function Corners(){return <><View style={[s.corner,s.tl]}/><View style={[s.corner,s.tr]}/><View style={[s.corner,s.bl]}/><View style={[s.corner,s.br]}/></>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#000'},header:{height:100,paddingHorizontal:32,alignItems:'center',justifyContent:'space-between',flexDirection:'row'},back:{width:70,height:70,borderWidth:1,borderColor:'#444',alignItems:'center',justifyContent:'center'},backText:{fontSize:54,color:'#fff',fontWeight:'200',marginTop:-10},top:{color:Colors.accent,fontSize:16,fontWeight:'900',letterSpacing:1.5},rule:{height:StyleSheet.hairlineWidth,backgroundColor:'#222',marginHorizontal:18},content:{padding:32,flex:1},eyebrow:{color:Colors.accent,fontSize:15,fontWeight:'900',letterSpacing:2.4,marginTop:33},title:{color:'#fff',fontSize:68,lineHeight:60,fontWeight:'900',letterSpacing:-3,marginTop:32},cameraBox:{height:520,borderWidth:StyleSheet.hairlineWidth,borderColor:'#444',marginTop:58,backgroundColor:'#0d0d0d',overflow:'hidden',justifyContent:'center'},corner:{position:'absolute',width:70,height:70,borderColor:Colors.accent,zIndex:2},tl:{top:'29%',left:'17%',borderTopWidth:5,borderLeftWidth:5},tr:{top:'29%',right:'17%',borderTopWidth:5,borderRightWidth:5},bl:{bottom:'29%',left:'17%',borderBottomWidth:5,borderLeftWidth:5},br:{bottom:'29%',right:'17%',borderBottomWidth:5,borderRightWidth:5},permission:{alignItems:'center',zIndex:3},cameraIcon:{fontSize:34,color:'#ccc'},permissionTitle:{color:'#ccc',fontSize:16,fontWeight:'900',letterSpacing:1.5,marginTop:15,borderTopWidth:2,borderTopColor:Colors.accent,paddingTop:10},permissionBody:{color:'#777',fontSize:16,marginTop:14},allow:{borderWidth:1,borderColor:Colors.accent,paddingHorizontal:18,paddingVertical:12,marginTop:22},allowText:{color:Colors.accent,fontWeight:'900',letterSpacing:1.3},footer:{color:'#777',fontSize:13,fontWeight:'900',letterSpacing:1.4,textAlign:'center',marginTop:32}});
